### PR TITLE
Prepare from TRLCustomReport marked as virtual

### PR DESCRIPTION
**Pull request by cdvdt**
Prepare method from TRLCustomReport as virtual so a custom behavior can be implemented over it, allowing changes on both previewing and printing reports

### CODE REVIEW

**Comment by cdvdt** [comment]
Fix for issue when cloning TRLPolygonObject

**Comment by cdvdt** [comment]
There are two proposed changes, on two separeted commits

1. Prepare from TRLCustomReport marked as virtual

2. Fix for issue when cloning TRLPolygonObject

**Comment by dopidaniel** [comment]
Looks like you change the File Encoding to UTF8... 

Fortes Report files should be on ANSI encoding, for Delphi 7 compatibility

**Comment by cdvdt** [comment]
I have fixed the coding from files, now it's both UTF-8

**Comment by dopidaniel** [comment]
Thanks... :)

**Pull request merged**
